janweb_blog/janweb_blog/urls.py
from os import name
from django.contrib import admin
from django.urls import path, re_path
from main_web import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),

    #reg and auth
    path('registration/', views.Registration),
    path('login/', views.Logining),
    path('logout/', views.Logout),
    path('login/wrong/', views.LoginingWrong),
    path('account/set-avatar', views.AccountSetAvatarReq),
    re_path(r'^account/', views.AccountPage),

    path('addpost/', views.PosteArticle),
    path('myposts/', views.MyPosts),
    path('post/', views.GetPost, name='full_post'),
    path('myposts/delete_post', views.DeletePostReq,  name='delete_post'),
    path('myposts/edit_user_post', views.EditPostsReq, name='edit_post'),
    path('addimage/', views.AddUserImageReq, name='add_image'),
    path('comment/post/', views.CommentArticleReq, name='comment_article'),
    path('get_post_ratings/', views.GetPostRatingsReq, name='get_post_ratings'),    
    path('set_user_rating_to_post/', views.SetUserRatingToPostReq, name = 'set_user_rating_to_post'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)   

janweb_blog/main_web/forms.py
from django import forms, setup
from django.contrib.auth import validators
from django.db import models
from django.forms import widgets
from django.forms.fields import CharField, ChoiceField
from .models import Category
from .logic.ArticleManager import GetCat
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
import re
from itertools import chain

class User_reg_form(forms.Form):
    login = forms.CharField(label='Your login')
    password = forms.CharField(label= 'Enter password', widget = forms.PasswordInput())
    password_again = forms.CharField(label='Enter password again', widget=forms.PasswordInput())
    email = forms.CharField(label='Enter your email')


class User_auth_form(forms.Form):
    user_login = forms.CharField(label='Your login')
    user_password = forms.CharField(label='Your pasword', widget=forms.PasswordInput())

#да, я знаю, что можно было создать форму на основе модели
class UserPostArticleForm(forms.Form):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def CreateCatList(cats):
        return [(cat, cat) for cat in cats]
    #ГЕНИЙ МЫСЛИ
    name = forms.CharField(
        min_length=10,
        max_length=255,
        label='Name of article',
        widget=forms.widgets.Textarea()
        )
    
    category = forms.ChoiceField(
        choices = CreateCatList(GetCat()),
        widget= forms.Select(attrs={'class': 'select_cat'})
        )

    short_description = forms.CharField(
        min_length=100,
        max_length=500, 
        widget=forms.widgets.Textarea(),
        label='Short description of article'
        )
    

    text =  forms.CharField(
        widget=forms.widgets.Textarea(attrs={'id': 'article_text'}), 
        min_length=1000,
        max_length=200000,
        label='Full text of article'
        )

class FilterPostsForm(forms.Form):
    
    def CreateCatList( cats):
        default_selec = 'all category'
        rez = [(cat, cat) for cat in cats]
        rez.insert(0, (None, default_selec))
        return rez

    class MyDateInput(forms.DateInput):
        input_type = 'date'
        format = '%Y-%m-%d'

    cat_filter = forms.ChoiceField(
        label='Category',
        widget=forms.Select(attrs={'class': 'select_cat' }), 
        required=False,
        choices = CreateCatList( GetCat())
    )

    str_filter = forms.CharField(
        label='Articles witch contains',
        min_length=1,
        max_length=100,
        widget = forms.TextInput(attrs={'class': 'search_field'}),
        required=False,
    )

    date_from_filter = forms.DateField(
        required = False,
        label='From date',
        widget=MyDateInput({
            'class': 'form-control date_field'
           })
        )

    date_to_filter   = forms.DateField(
        required=False,
        label='To date',
        widget=MyDateInput({
            'class': 'form-control date_field'
           })
        )


class CommentForm(forms.Form):
    comment_text = forms.CharField(
        required=True,
        max_length=5000,
        min_length=5,
        label='Your comment',
        widget=forms.widgets.Textarea(attrs={'class': 'comment_form_text'}),
    )

janweb_blog/templates/auth_user_header.html
{%load static%}
<script type="text/javascript">
    $(document).ready(
        function(){
            $('#user_block nav').hide()
            $('#user_block').hover(
                function(){
                    $('#user_block nav').stop().fadeToggle(200)
                }
            )
        }
    )
</script>
<div id = 'user_block'>
    <div id="main_user_visible">
        <img src={{profile_img}} alt="profile_img" width="40px" height="40px">
        <p>{{user}}</p>
    </div>
    <nav>
        <ul id="user_block_submenu">
            <li><a href="/account/{{user}}">Account</a></li>
            <li><a href="/myposts"> My posts</a></li>
            <li><a href="/addpost">New post<img src="{%static 'images/icons/submenu_plus_to_new_post.svg'%}" alt="+" class="plus_in_submenu"></a></li>
            <li><a href="/logout">Exit</a></li>
        </ul>    
    </nav>
</div>

janweb_blog/templates/fullpost_page.html
{%extends 'index.html'%}

{%block auth_header_user%}
    {%if is_auth%}
        {%include 'auth_header_user.html'%}
    {%else%}
        <div class = 'h_nav_item'><a href="/registration">SigIn</a></div>
        <div class = 'h_nav_item'><a href="/login"       >LogIn</a></div>    
    {%endif%}
{%endblock%}

{%block content%}
{%load static%}

<script>
    const GetArticleRating = (post_id)=>{
        likes = undefined
        dislikes = undefined
        $.ajax({
            data: {
                post_id: post_id,
            },

            url: "{%url 'get_post_ratings'%}",
            success: (res)=>{
                console.log('Post rating has been recieved')
                likes = res.likes
                dislikes = res.dislikes
                $('.counter_likes').text(likes)
                $('.counter_dislikes').text(dislikes)
                console.log('update, likes: ', likes, '\tdislikes: ', dislikes)
            },
            error: (res)=>{
                console.log('Error getting post ratings')
                console.log(res.err)
            },
        })
    }

    const SendUserRating = (method = undefined, post_id)=>{
        const acceslist = ['like', 'dislike']
        if(acceslist.indexOf(method) != -1){
            $.ajax({
                data: {
                    method: method,
                    post_id: post_id,
                },

                url: "{%url 'set_user_rating_to_post'%}",

                success: (res)=>{
                    console.log('User succes send the: ', method)
                    console.log(res.res)
                    GetArticleRating(post_id)
                },

                error: (res)=>{
                    console.log('Error sending the: ', method)
                },
            })
        }
    }

    $(document).ready(
        function()
        {   
            post_id = $('#post').attr('post_id')
            GetArticleRating(post_id)
            $('.like_button').on('click', function(){
                SendUserRating('like', post_id)
            })
            $('.dislike_button').on('click', function(){
                SendUserRating('dislike', post_id)
            })
        }
    )
</script>

<link rel="stylesheet" href="{% static 'css/fullpost_page.css' %}">
<div id="main_place_post">
    <div  id = 'post' class="fullpost_borders" post_id = {{post.id}}>
        <div class = 'post_author'>
            <div class = 'author_block'>
            {{post.author}}
            </div>
        </div>
        <div class = 'name_of_full_post text_wrap_overflow'>
            {{post.name}}
        </div>
        <div class = 'categories'>
            {%for ct in post.cat%}
            <div class = 'cat'>
                {{ct}}
            </div>    
            {%endfor%}
        </div>
        <div class = 'shr_desc_full_post text_wrap_overflow'>
            {{post.shrt_desc}}
        </div>
        <div class = 'text text_wrap_overflow'>
            {{post.text|safe}}
        </div>    
        <div class="post_rating_field">
            <div class="rating_item">
                <button class="img_button_raiting like_button">
                    <img src="{%static 'images/icons/like.svg'%}" alt="like">
                    <span class="counter_likes"></span>
                </button>
            </div>
            <div class="rating_item">
                <button class="img_button_raiting dislike_button">
                    <img src="{%static 'images/icons/dislike.svg'%}" alt="dislike">
                    <span class="counter_dislikes"></span>
                </button>
            </div>
        </div>
    </div>
    <div id="fullpost_bottom" class= "fullpost_borders">
        {%if is_auth%}
        <form action="/comment/post/" method="POST" class="comment_form">
            {%csrf_token%}
            <p>Your comment: </p>
            {{comment_form.comment_text}}
            <input name="post_id" type="hidden" value = {{post.id}}>
            <input class="submit_comment" type="submit" value = 'Send comment'>
        </form>
        {%endif%}
        <div class="comments_field">
            <ul class="comments_list">
                {%for comment in comments%}
                <li>
                    <p class="auth_cmt">{{comment.user}}</p>
                    <p class="txt_cmt">{{comment.text}}</p>
                    <p class="dt_cmt">{{comment.pub_datetime}}</p>
                </li>
                {%endfor%}
            </ul>
        </div>
    </div>
</div>

<div id = 'navpult' class="fullpost_borders">

</div>
{%endblock%}

janweb_blog/templates/index.html
<!DOCTYPE html>
{%load static%}
<html>
<header>
    <meta charset="utf-8">
    <title>Litblog</title>
    <link rel="stylesheet" href="{%static 'css/header.css'%}">
    <link rel="stylesheet" href="{%static 'css/content.css' %}">
    <link rel="stylesheet" href="{%static 'css/footer.css'%}">
    <link rel="stylesheet" href="{%static 'css/index.css'%}">
    <link rel="stylesheet" href="{%static 'css/fonts.css'%}">
    <link rel="stylesheet" href="{%static 'css/articles_container.css'%}">
    <link rel="stylesheet" href="{%static 'css/article_filter.css'%}">
    <link rel="stylesheet" href="{%static 'css/header_user_block.css'%}">
    <script type="text/javascript" src="{%static 'js/jquery-3.6.0.js'%}"></script>
</header>
<body>
    <div class = 'Header'>
        <div class = 'h_item'>
            <div class = 'logo' >
                <a href="/">
                    Litblog
                </a>
            </div>
            <div class = 'header_navbar'>
                    <div class = 'h_nav_item'><a href="/about"       >About</a></div>
                {%if is_auth%}
                    {% include 'auth_user_header.html' %}
                {%else%}
                    <div class = 'h_nav_item'><a href="/registration">SigIn</a></div>
                    <div class = 'h_nav_item'><a href="/login"       >LogIn</a></div>
                {%endif%}    
            </div>
        </div>
    </div>
    <div class = 'navbar'>
        {%block navbar%}

        {%endblock%}
    </div>
    <div class = 'content'>
        {%block content%}
        <div id = 'articles_container'>
            {%for post in articles%}
            <div class = 'box_post'>
                <a href="/">
                    <div class="box_post_user ">
                        {{post.author}}
                    </div>
                </a>
                <a href="/post/?id={{post.id}}">
                    <div class = 'name_of_post text_wrap_overflow'>
                        {{post.name}}
                    </div>    
                </a>
                <div class = 'category'>
                    {%for category in post.cat%}
                    <div class = 'cat_item'>
                        {{category}}
                    </div>
                    {%endfor%}
                </div>
                <div class = 'description text_wrap_overflow'>
                    {{post.shrt_desc}}
                </div>
                <div class = 'datetime_post'>
                    {%if post.date_post and post.time_post%}
                    <p> 
                        {%if post.changed_flag%}
                        <span>Changed: </span>
                        {%endif%}
                        {{post.date_post}}
                        {{post.time_post}}
                    </p>
                    {%endif%}
                </div>
            </div>
            {%endfor%}    
        </div>
        <div id = 'pult_main_page'>
            <div id = 'filter_field'>
                <p>SEARCH</p>
                <form method="GET">
                    {%csrf_token%}
                    {%for item in FilterForm%}
                    <div class = 'filter_item'>
                        <div class = 'label_filter_field'>{{item.label}}</div>
                        <div class = '{{item.name}} input_field'>{{item}}</div>
                        {{item.errors}}
                    </div>
                    {%endfor%}
                    <input type="submit" value="Search" id = 'filter_submit'>
                </form>
            </div>
        </div>
        {%endblock%}
    </div>
    <div id = 'footer'>
        {%block footer%}

        {%endblock%}
    </div>    
</body>
</html>

janweb_blog/templates/login.html
{%extends 'index.html'%}
{%block content%}
{%load static%}
<link rel="stylesheet" href="{%static './css/logining.css'%}">
<div class="log_container">
    <div class = 'logining common_border'>
        <div class = 'logo_log'>
            Login
        </div>
        <form method="POST">
            {%csrf_token%}
            {% for item in form %}
            <div class = 'log_form_item'>
                <div class = 'field_label'>{{item.label}}</div>
                <div class = 'field'>{{item}}</div>
            </div>
            {% endfor %}
            <input type="submit" value="Enter">
        </form>
        {% if is_wrong == True  %}
        <div class="error_mess">
            Error data
        </div>
        {% endif %}
    </div>    
</div>
{%endblock%}

janweb_blog/templates/poste_article.html
{%extends 'index.html'%}




{%block content%}
{%load static%}
<link rel="stylesheet" href="{%static 'css/post_page.css'%}">

<link rel="stylesheet" href="{%static 'js/trumbowyg/dist/ui/trumbowyg.min.css'%}">
<script type="text/javascript" src="{%static 'js/trumbowyg/dist/trumbowyg.js'%}"></script>
<script type="text/javascript" src="{%static 'js/trumbowyg/dist/plugins/upload/trumbowyg.upload.min.js'%}"></script>
<script src="//rawcdn.githack.com/RickStrahl/jquery-resizable/0.35/dist/jquery-resizable.min.js"></script>
<script type="text/javascript" src="{%static 'js/trumbowyg/dist/plugins/resizimg/trumbowyg.resizimg.min.js'%}"></script>

<script type="text/javascript">

    function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
    }

    $(document).ready(function(){
        $('#article_text').trumbowyg(
        {   
            tagsToRemove: ['script', 'link'],
            btnsDef: {
            // Create a new dropdown
                image: {
                    dropdown: ['insertImage', 'upload'],
                    ico: 'insertImage'
                }
            },
            // Redefine the button pane
            btns: [
                ['viewHTML'],
                ['formatting'],
                ['strong', 'em', 'del'],
                ['superscript', 'subscript'],
                ['link'],
                ['image'], // Our fresh created dropdown
                ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
                ['unorderedList', 'orderedList'],
                ['horizontalRule'],
                ['removeformat'],
                ['fullscreen']
            ],
            plugins: {
                // Add imagur parameters to upload plugin for demo purposes
                upload: {
                    serverPath: "{%url 'add_image'%}",
                    fileFieldName: 'image',
                    headers: { "X-CSRFToken": getCookie("csrftoken") },
                },
                resizimg: {
                    minSize: 100,
                    step: 5,
                },
            }
        })
    })    
</script>


<div class = 'post_article_page'>
    <div id = 'article_add_form' class="common_border">
        <form method="POST">
            {%csrf_token%}
            {%for item in ArticlePost%}
            <div id = 'form_item'>
                <div class = 'label'>
                    <div>{{item.label}}</div>
                </div>
                <div class = 'form_item'>
                    <div> {{item}}</div>   
                </div>
            </div>
            {%endfor%}
            <div class = 'submit_button'>
                {%if post_id_to_edit%}
                <input type="hidden" name="post_id" value={{post_id_to_edit}}>
                <input type='submit' value="Save changes ">
                {%else%}
                <input type="submit" value="Post">
                {%endif%}
            </div>
        </form>    
    </div>
    <div id = 'side_addpost_page' class="common_border">
        
    </div>
</div>
{%endblock%}

janweb_blog/templates/registration.html
{%extends 'index.html'%}
{%block content%}
{%load static%}
<link rel="stylesheet" href="{% static 'css/registration.css' %}">
<div class="reg_container">
    <div class = 'registration common_border'>
        <p class="reg_header">Registration</p>
        <form method="POST">
            {%csrf_token%}
            {% for item in form %}
            <div class = 'reg_form_item'>
                <div class = 'field_label'>{{item.label}}:</div>
                <div class = 'field'>{{item}}</div>
            </div>
            {%endfor%}
            <input type='submit' value="Register">
        </form>
        {%if error %}
            <div class='error_mess'>
                {{error}}
            </div>
        {%endif%}
    </div>    
</div>
{%endblock%}

janweb_blog/templates/user_posts_page.html
{%extends 'index.html'%}



{%block content%}
{%load static%}

<script type="text/javascript">
    $(document).ready(function(){
        $('#confirm_of_deleting_post').hide()
        $('.delete_post_button').click(function(){
            const post_id = $(this).attr('post_id')
            delete_button = this
            confirm_delete = false
            html_elem  = '#' + post_id+'.art_name'
            post_name = $(html_elem).text()
            console.log('ID: ', post_id, '\tNAME: ', post_name, '\tHTML ELEMENT: ', html_elem)
            $('#deleting_post_name').append(
                '<p>"'+ post_name+ '" ?</p>'
            )
            $('#confirm_of_deleting_post').show()
    
            $('#confirm_of_deleting_post .delete').click(function(){
                $.ajax({
                    data: {
                        post_id: post_id,
                    },

                    url: "{% url  'delete_post' %}",
                    success: (res)=>{
                        console.log('post deleted, response server: ', res.result)
                    },
                    error: (res)=>{
                        alert('SERVER ERROR')
                    },
                })
                $('#confirm_of_deleting_post').hide()
                $(delete_button).addClass('activate_delete_button')
            })

            $('#confirm_of_deleting_post .cancel').click(function(){
                $('#confirm_of_deleting_post').hide()
            })

        })

    })

</script>

<link rel="stylesheet" href="{%static 'css/user_posts_page.css'%}">
<div id = 'posts_look_edit'>
    <div id = 'filter_user_posts'>
        <form method="GET">
            {%csrf_token%}
            <div id = 'search_main'>
                {{filter_form.str_filter}}
                <input id = 'user_filter_submit' type="submit" value="FILTER">
            </div>
            <div id = 'over_parametres'>
                <div id = 'cat'>{{filter_form.cat_filter}}</div>
                <div id ='dates'>
                    <span>
                        <label for="id_date_from_filter">Date from:</label>
                        {{filter_form.date_from_filter}}        
                    </span>
                    <span>
                        <label for="id_date_tofilter">To date:</label>
                        {{filter_form.date_to_filter}}        
                    </span>
                </div>
            </div>
        </form>
    </div>
    <div id = 'user_posts_container'>
        {%for art in user_articles%}
        <div class = 'user_post_box'>
            <div class = 'post_content'>
                <p id={{art.id}} class = 'art_name text_wrap_overflow'><a href="/post/?id={{art.id}}">{{art.name}}</a></p>
                <div class = 'category'>
                    {%for category in art.cat%}
                    <div class = 'cat_item'>
                        {{category}}
                    </div>
                    {%endfor%}
                </div>
                <p class = 'art_desc text_wrap_overflow'>{{art.shrt_desc}}</p>
                {%if art.date_post and art.time_post%}
                <p class = 'art_datetime'>
                    <span>Changed: </span>
                    {{art.date_post}} 
                    {{art.time_post}}
                </p> 
                {%endif%}   
            </div>
            <div class="edit_options">
                <a href="/myposts/edit_user_post?post_id={{art.id}}">
                    <div post_id = {{art.id}} class="edit_post_button edit_item">
                        <img src="{%static 'images/edit_posts_page/edit_post.svg'%}" alt="edit">
                    </div>    
                </a>
                <div post_id = {{art.id}} class="delete_post_button edit_item">
                    <img src="{%static '/images/edit_posts_page/delete_post.svg'%}" alt ="delete">
                </div>
            </div>
        </div>
        {%endfor%}
    </div>
</div>

<div id = 'confirm_of_deleting_post'>
    <div class="float_window">
        <p id = 'deleting_post_name'>Are you sure that you want delete post:</p>
        <div class="bottom_box">
            <button class ='delete'>Delete</button>
            <button class ='cancel'>Cancel</button>        
        </div>
    </div>
</div>

<div class = 'side_panel_edit_posts_page'>

</div>
{%endblock%}

janweb_blog/templates/user_profile.html
{%extends 'index.html'%}

{%block content%}
{%load static%}
<link rel="stylesheet" href="{%static 'css/user_profile.css'%}">
<div class = 'user_profile'>
    <div class = 'profile_avatar block_border_profile'>
        <p class="username">{{Profile.username}}</p>
        <!--<img class="img_avatar" src='https://vraki.net/sites/default/files/inline/images/10_342.jpg' alt="avatar">-->
        <img src={{Profile.avatar_url}} alt="avatar">
        <form id ='set_avatar' method="post" action='/account/set-avatar' enctype="multipart/form-data">
            {%csrf_token%}
            <div class="sl_file">
                <input class="file_button" id="file" name="avatar" type="file" accept="image/png, image/jpeg, image/jpg">
            </div>
            <input class="send_file" type="submit" value="Load">
        </form>
    </div>
    <div class="main_field_profile block_border_profile">
        <div class="user_container">
            <p class="username_main">{{Profile.username}}</p>
            <p class="date_registration">Registrated: <span>{{Profile.date_registration}}</span></p>
        </div>
        <div class="user-inf">
            <ul class="statistic_list">
                <li>Your articles:  <span>{{Profile.articles}}</span></li>
                <li>Your likes:     <span>{{Profile.likes}}</span></li>
                <li>Your diselikes: <span>{{Profile.dislikes}}</span></li>
                <li>Your comments:  <span>{{Profile.comments}}</span></li>
            </ul>            
        </div>
    </div>

</div>

{%endblock%}